name: deploy 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16' # Using LTS version of Node.js

    - name: Install Dependencies
      run: npm install

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.10'

    - name: List files for debugging
      run: |
        ls -R

    - name: Build static website
      run: |
        go run cmd/build/main.go

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
